In [31]:
class MyLinearReg:

     def __init__(self):
         self.m = None
         self.b = None

     def fit(self,X_train,y_train):
         num = 0
         den = 0
         for i in range(X_train.shape[0]):
             num += ((X_train[i] - X_train.mean()) * (y_train[i] - y_train.mean()))
             den += ((X_train[i] - X_train.mean()) * (X_train[i] - X_train.mean()))

         self.m = num / den
         self.b = y_train.mean() - (self.m * X_train.mean())
         
         print(self.m)
         print(self.b)
         
     def predict(self,X_test):
         return self.m * X_test + self.b

In [5]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('students_cgpa_package.csv')

In [9]:
df.head()

CGPA  Package_LPA
0  8.20        11.35
1  6.38         9.02
2  8.68        13.37
3  9.46        13.36
4  7.11         9.72

In [11]:
X = df.iloc[:,0].values

In [13]:
X


array([ 8.2 ,  6.38,  8.68,  9.46,  7.11,  6.09,  5.13,  8.25,  6.1 ,
        9.05,  9.03,  6.7 ,  9.79,  5.46,  9.24,  9.04,  7.68,  6.89,
        9.15,  9.31,  8.52,  6.14,  5.4 ,  5.51,  8.18,  6.85,  6.33,
        8.24,  5.86,  5.82,  9.95,  7.78,  9.21,  6.15,  6.58,  6.05,
        9.38,  8.28,  9.57,  6.32,  7.81,  7.92,  7.  ,  9.99,  5.45,
        5.55,  8.96,  5.32,  9.98,  9.86,  5.06,  8.41,  6.33,  5.56,
        7.27,  9.38,  7.5 ,  9.56,  6.49,  8.04,  8.81,  8.89,  5.  ,
        5.1 ,  9.39,  6.54,  9.39,  5.43,  5.35,  8.83,  7.38,  6.33,
        7.12,  7.7 ,  6.01,  9.98,  7.19,  5.61,  6.69,  6.15,  5.35,
        6.14,  9.3 ,  6.19,  6.07,  9.68,  7.36,  9.04,  5.48,  7.12,
        8.65,  9.92,  7.01,  9.31,  5.95,  7.11,  6.25,  7.22,  7.75,
       10.  ,  9.84,  9.24,  7.43,  7.01,  6.89,  6.33,  7.28,  9.79,
        7.78,  5.77,  9.84,  7.71,  5.29,  7.51,  5.79,  5.4 ,  7.98,
        6.18,  9.45,  7.97,  7.1 ,  7.61,  6.02,  6.19,  8.36,  6.58,
        5.36,  9.99,

In [15]:
y = df.iloc[:,1].values

In [17]:
y

array([11.35,  9.02, 13.37, 13.36,  9.72,  9.15,  7.09, 12.46,  9.33,
       12.59, 13.94,  9.36, 14.36,  7.38, 14.07, 14.02, 12.47, 10.44,
       13.96, 14.12, 11.87,  8.79,  7.57,  7.82, 12.  ,  9.69, 10.37,
       12.58,  9.25,  8.49, 15.2 , 12.04, 14.37,  8.29,  9.41,  9.96,
       13.7 , 12.21, 14.27,  8.97, 11.24, 12.68,  9.94, 15.  ,  7.27,
        8.58, 13.28,  7.74, 15.03, 15.51,  8.03, 12.69,  9.78,  8.21,
       11.81, 13.6 , 10.61, 15.08, 10.01, 11.37, 13.29, 13.4 ,  7.15,
        8.51, 14.75,  8.93, 14.98,  8.12,  8.55, 12.5 , 11.17, 10.24,
       10.1 , 12.01,  8.64, 15.27, 10.82,  7.86, 10.21,  8.67,  8.29,
       10.02, 13.09,  9.62,  8.37, 14.66, 11.61, 12.94,  8.08, 10.61,
       13.32, 14.08, 10.19, 13.46,  8.82, 10.22, 10.22, 11.55, 10.73,
       15.67, 15.61, 13.19, 10.57,  9.63, 11.31, 10.06, 10.77, 15.68,
       12.11,  8.25, 14.92, 12.06,  8.1 , 11.97,  9.61,  7.47, 12.32,
        8.51, 13.67, 12.19, 10.82, 12.28,  9.46,  9.08, 12.14, 10.37,
        7.96, 15.98,

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 2)

In [33]:
lr = MyLinearReg()

In [35]:
lr.fit(X_train,y_train)

1.5089996449505405
-0.028052751484269223


In [37]:
X_test

array([5.29, 5.82, 6.93, 8.27, 5.64, 9.68, 9.03, 7.27, 5.4 , 6.05, 9.79,
       7.01, 5.46, 5.36, 8.21, 8.68, 5.45, 9.46, 7.51, 9.24, 5.51, 6.85,
       5.13, 8.27, 9.05, 9.83, 5.55, 6.54, 9.98, 6.02, 9.81, 9.39, 9.05,
       9.56, 6.69, 6.33, 5.37, 9.7 , 6.85, 5.56])

In [39]:
y_test

array([ 8.1 ,  8.49, 10.55, 12.33,  8.3 , 14.66, 13.94, 11.81,  7.47,
        9.96, 14.36, 10.19,  7.38,  7.96, 12.11, 13.37,  7.27, 13.36,
       11.97, 14.07,  7.82,  9.69,  7.09, 11.42, 13.11, 14.3 ,  8.58,
        8.93, 15.03,  9.46, 14.25, 14.75, 12.59, 15.08, 10.21, 10.24,
        7.48, 13.78,  9.59,  8.21])

In [45]:
lr.predict(X_test[0])

7.9545553703040905